language: emacs-lisp
env:
  matrix:
    - EMACS=emacs
    - EMACS=emacs24 EMACS_PPA=ppa:cassou/emacs
    - EMACS=emacs-snapshot EMACS_PPA=ppa:cassou/emacs
    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot EMACS_PPA=ppa:cassou/emacs
    - env: EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
before_install:
  # Install Emacs
  - if [ -n "$EMACS_PPA" ]; then
      sudo add-apt-repository -y "$EMACS_PPA";
    fi
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes -qq "$EMACS"
  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true  # OK to fail
script:
  - make travis-ci
